
### Send POST request with json body
POST http://localhost:8000/api/categories
Content-Type: application/json

{
    "name": "mateles2",
    "description": "para adornar la mesa2"
}
### Send GET request
GET http://localhost:8000/api/categories

### Send GET request with query parameters
